### POST schedule
POST http://localhost:8080/api/schedule
Content-Type: application/json
Authorization: Basic asd

{
  "id": "2",
  "memberId": "7734347",
  "scheduledTime": "2023-12-01T11:00:00+00:00"
}
### POST schedule out
POST https://gym-scheduler-nebp.onrender.com/api/schedule
Content-Type: application/json
Authorization: Basic asd

{
  "id": "33243027",
  "scheduledTime": "2025-04-21T18:31:00+00:00"
}
### GET schedule
GET http://localhost:8080/api/schedule/process/33243027
Authorization: Basic asd

### GET schedule
GET http://localhost:8080/api/schedule/list/2
Authorization: Basic asd

### GET schedule
GET https://gym-scheduler-nebp.onrender.com/api/schedule/list/2
Content-Type: application/json
Authorization: Basic asd

### GET home
GET https://gym-scheduler-nebp.onrender.com/
Content-Type: application/json
